<a href="https://colab.research.google.com/github/anurraggg/pytorch_learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [99]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


#Intro to Tensors
#Creating Tensors

In [100]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [101]:
scalar.ndim

0

In [102]:
#Getting Tensor back as Python int
scalar.item()

7

In [103]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [104]:
vector.ndim

1

In [105]:
vector.shape

torch.Size([2])

In [106]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [107]:
MATRIX.ndim

2

In [108]:
MATRIX[0]

tensor([7, 8])

In [109]:
MATRIX.shape

torch.Size([2, 2])

In [110]:
#TENSOR
TENSOR=torch.tensor([[[2,3,1],[5,6,7],[66,67,68]]])
TENSOR

tensor([[[ 2,  3,  1],
         [ 5,  6,  7],
         [66, 67, 68]]])

In [111]:
TENSOR.ndim

3

In [112]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensor

In [113]:
 #Create random tensor of size (2,3,4)
 #basically 2 dimensions of 3 by 4 matrix
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.7068, 0.2244, 0.9810, 0.8439],
         [0.5796, 0.9547, 0.4691, 0.5518],
         [0.1167, 0.9634, 0.7178, 0.1597]],

        [[0.3516, 0.0377, 0.5088, 0.6027],
         [0.2907, 0.8678, 0.7694, 0.0077],
         [0.7331, 0.1946, 0.0753, 0.9205]]])

In [114]:
random_tensor.ndim

3

In [115]:
random_tensor.shape

torch.Size([2, 3, 4])

In [116]:
#Creating a random tensor with a similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height, width, colour
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

ZEROs and ONEs

In [117]:
#create a tensor of all zeros
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [118]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [119]:
#Creating tensor of all ones

In [120]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [121]:
ones*random_tensor

tensor([[[0.7068, 0.2244, 0.9810, 0.8439],
         [0.5796, 0.9547, 0.4691, 0.5518],
         [0.1167, 0.9634, 0.7178, 0.1597]],

        [[0.3516, 0.0377, 0.5088, 0.6027],
         [0.2907, 0.8678, 0.7694, 0.0077],
         [0.7331, 0.1946, 0.0753, 0.9205]]])

In [122]:
zeros.dtype

torch.float32

In [123]:
ones.dtype

torch.float32

Creating a range of tensors

In [124]:
one_to_ten=torch.arange(start=1, end=11, step=0.5)
one_to_ten

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000])

In [125]:
#creating tensors like
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [126]:
ten_ones=torch.ones_like(one_to_ten)
ten_ones.dtype

torch.float32

In [127]:
ten_zeros*ten_ones

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [128]:
#converting frm float32 to float16
float_16_tensor=one_to_ten.type(torch.float16)
float_16_tensor

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000], dtype=torch.float16)

In [130]:
float_32_tensor=one_to_ten.type(torch.float32)
float_32_tensor

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000])

In [132]:
#so basically i can sometimes multiply float16 with float32
float_16_tensor*float_32_tensor

tensor([  1.0000,   2.2500,   4.0000,   6.2500,   9.0000,  12.2500,  16.0000,
         20.2500,  25.0000,  30.2500,  36.0000,  42.2500,  49.0000,  56.2500,
         64.0000,  72.2500,  81.0000,  90.2500, 100.0000, 110.2500])

### Getting information from tensor
1. Tensors not correct datatype - Use tensor.dtype to know and change dtype
2. Tensors not right shape - Use tensor.shape
3. Tensor not on right device - use tensor.device to know device eg- cpu or gpu

In [135]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.8294, 0.6237, 0.6646, 0.6946],
        [0.3965, 0.2450, 0.8508, 0.4478],
        [0.3111, 0.4696, 0.3950, 0.9889]])

In [144]:
#finding out details of tensor attribute
print(some_tensor)
print(f"datatype of tensor is: ", some_tensor.dtype)
print(f"shape of tensor is:",some_tensor.shape)
print(f"device of tensor is:", some_tensor.device)

tensor([[0.8294, 0.6237, 0.6646, 0.6946],
        [0.3965, 0.2450, 0.8508, 0.4478],
        [0.3111, 0.4696, 0.3950, 0.9889]])
datatype of tensor is:  torch.float32
shape of tensor is: torch.Size([3, 4])
device of tensor is: cpu


### Tensor Operations which include + , -- , / , * , Matrix Multiplication

In [146]:
#addition
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [148]:
#Multiplication
tensor*10

tensor([10, 20, 30])

In [150]:
#Subtract
tensor-10

tensor([-9, -8, -7])

In [157]:
#Division
dec_tensor = tensor/10
dec_tensor # output is in float32

tensor([0.1000, 0.2000, 0.3000])

In [163]:
#Matrix Multiplication
#Element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [166]:
#Matrix multiplication
torch.matmul(tensor, tensor) #torch.matmul() is a function to do matrix multiplication

tensor(14)

RULES OF MATRIX MULTIPLICATION:
1) The inner dimensions must match:

*   (3,2) @ (3,2) wont work
*   (2,3) @ (3,2) will work
*   (3,2) @ (2,3) will work

2) The output has the shape of outer dimension







In [173]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.6022, 0.7735, 0.8599],
        [0.3821, 0.4586, 0.5277],
        [0.4401, 0.6241, 0.6613]])

In [171]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.3852, 0.9609],
        [0.4895, 1.6706]])

In [172]:
torch.rand(2,3)

tensor([[0.0324, 0.4545, 0.3626],
        [0.5038, 0.8191, 0.8796]])

In [178]:
#shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tensor_B=torch.tensor([[7,10],
                      [8,11],
                      [9,12]])

torch.matmul(tensor_A, tensor_B)
#we can also use torch.mm()
#output is wrong cuz inner dimension dont match

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

#to fix our tensor shape issue we can manipulate the shape of one of the tensor using *transpose*


In [181]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [184]:
output_of_tensor_A_and_B = torch.matmul(tensor_A, tensor_B.T)
output_of_tensor_A_and_B

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [186]:
output_of_tensor_A_and_B.shape
#the outer dimensions of the output matches

torch.Size([3, 3])