In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


#Intro to Tensors
#Creating Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Getting Tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR=torch.tensor([[[2,3,1],[5,6,7],[66,67,68]]])
TENSOR

tensor([[[ 2,  3,  1],
         [ 5,  6,  7],
         [66, 67, 68]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensor

In [16]:
 #Create random tensor of size (2,3,4)
 #basically 2 dimensions of 3 by 4 matrix
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.4184, 0.2622, 0.3205, 0.8288],
         [0.4939, 0.8623, 0.7483, 0.7630],
         [0.3128, 0.5369, 0.3829, 0.0980]],

        [[0.3253, 0.5109, 0.4471, 0.2928],
         [0.5444, 0.7468, 0.0906, 0.5081],
         [0.9517, 0.5114, 0.8326, 0.4893]]])

In [17]:
random_tensor.ndim

3

In [18]:
random_tensor.shape

torch.Size([2, 3, 4])

In [19]:
#Creating a random tensor with a similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height, width, colour
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)